Pre Final
ntsmoura/estudosKotlin pull request #1
Opened 2020-03-09 02:35 UTC by ntsmoura

Revisaaaa

2020-03-09 16:52 UTC, pablohildo requested changes

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/.idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Esse tipo de arquivo não devia ser versionado. Olhar https://www.gitignore.io/

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/activities/DescriptionActivity.kt
> +        textView6.text = descript
É ideal que você dê um id legível pra suas views. O padrão usado na Cubos, por exemplo, seria algo como `overviewTXT` e `bannerIMG`

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/activities/MainActivity.kt
> +        recyclerView = recyclerV
Existe necessidade real disso? Qual o caso de uso em que não faz sentido simplesmente usar o recycler que você ja tem?

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/activities/MainActivity.kt
> +                    listMovies.addAll(response.body()!!.results)
O uso de double-bang (`!!`) é desencorajado porque é uma das únicas formas de causar uma NPE (Null Pointer Exception) em Kotlin.
Ref: https://kotlinlang.org/docs/reference/null-safety.html

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/activities/MainActivity.kt
> +                    "Não foi possível encontrar filmes, verifique a conexão!",
Toda string exibida deve estar no arquivo `strings.xml` e ser obtida de lá, por motivos relacionados a internacionalização e manutenibilidade
Ref: https://developer.android.com/guide/topics/resources/string-resource

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/adapters/MovieAdapter.kt
> +        val movie: Results = movieList[position]
Você não precisa especificar o tipo, porque `movieList` é um `List<Results>`, e, portanto, qualquer item só pode ser do tipo `Results`. É redundante.

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/adapters/MovieAdapter.kt
> +        holder.movieTextView.text = movie.title
Veja `with` e `apply para as linhas seguintes.
https://kotlinlang.org/docs/reference/scope-functions.html

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/adapters/MovieAdapter.kt
> +        val movieTextView = itemView.findViewById(R.id.textView2) as TextView
Em toda aplicação você usa synthetic (pegar id diretamente do xml), por que aqui usa `findViewById`? Além disso, no Kotlin, você pode explicitar o tipo na chamada dessa função sem precisar fazer casting, que é levemente unsafe:
`itemView.findViewById<TextView>(R.id.textView2)`

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/utils/TmdbInterface.kt
> +    @GET("popular?")
`?` em popular é desnecessário aqui

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/models/PopularMovies.kt
> +    @SerializedName("results") val results : List<Results>
Se me lembro bem, você não precisa de `@SerializedName` se o nome é igual ao da variável

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/models/Results.kt
>      @SerializedName("poster_path") val poster_path : String,
Variável tem identificador em camelCase em Kotlin, não snake_case.
https://developer.android.com/kotlin/style-guide
Notar comentário anterior também

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/res/layout/activity_description.xml
> +
Verificar o que já foi dito sobre `id` de views

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="349dp"
Valores fixos assim pra largura e altura quase sempre vão ser problemáticos em diferentes tamanhos de tela e geralmente são casos em que a aplicabilidade de ConstraintLayout é provável.

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/res/layout/activity_main.xml
>          android:layout_marginBottom="35dp"
Valores muito arbitrários para as margens, provavelmente devem ser revistos

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/res/layout/movie_layout.xml
> +        android:id="@+id/card_v"
Padronizar id

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/res/layout/movie_layout.xml
> +                android:focusable="auto" />
Valor padrão de focusable é auto, não tem motivo pra mudar ele

2020-03-09 16:52 UTC, pablohildo commented on TopMovies/app/src/main/res/values/strings.xml
> +    <string name="descript">Descrição</string>
```suggestion
    <string name="description">Descrição</string>
```

2020-03-10 12:39 UTC, ntsmoura commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/activities/DescriptionActivity.kt
> +        textView6.text = descript
Alterados os Ids de todas as Views

2020-03-10 13:24 UTC, ntsmoura commented on TopMovies/.idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
gitignore feito

2020-03-10 13:25 UTC, ntsmoura commented on TopMovies/app/src/main/res/layout/movie_layout.xml
> +        android:id="@+id/card_v"
Personalizada

2020-03-10 13:26 UTC, ntsmoura commented on TopMovies/app/src/main/res/values/strings.xml
> +    <string name="descript">Descrição</string>
feito

2020-03-10 13:26 UTC, ntsmoura commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/adapters/MovieAdapter.kt
> +        val movieTextView = itemView.findViewById(R.id.textView2) as TextView
usei synthetic

2020-03-10 13:27 UTC, ntsmoura commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/models/PopularMovies.kt
> +    @SerializedName("results") val results : List<Results>
retirados serializeds para nomes iguais

2020-03-10 13:27 UTC, ntsmoura commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/models/Results.kt
>      @SerializedName("poster_path") val poster_path : String,
formatado em camelCase

2020-03-10 13:27 UTC, ntsmoura commented on TopMovies/app/src/main/res/layout/activity_description.xml
> +
Ids padronizadas

2020-03-10 13:35 UTC, ntsmoura commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/activities/MainActivity.kt
> +        recyclerView = recyclerV
Alterado

2020-03-10 13:41 UTC, ntsmoura commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/activities/MainActivity.kt
> +                    listMovies.addAll(response.body()!!.results)
Retirado o double-bang e alterada a construção do código

2020-03-10 13:42 UTC, ntsmoura commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/activities/MainActivity.kt
> +                    "Não foi possível encontrar filmes, verifique a conexão!",
Feito

2020-03-10 13:43 UTC, ntsmoura commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/adapters/MovieAdapter.kt
> +        val movie: Results = movieList[position]
Feito

2020-03-10 13:45 UTC, ntsmoura commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/utils/TmdbInterface.kt
> +    @GET("popular?")
feito

2020-03-10 13:52 UTC, ntsmoura commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/adapters/MovieAdapter.kt
> +        holder.movieTextView.text = movie.title
feito

2020-03-10 13:55 UTC, ntsmoura commented on TopMovies/app/src/main/res/layout/activity_main.xml
> +        android:layout_width="349dp"
tamanho revisto

2020-03-10 14:00 UTC, ntsmoura commented on TopMovies/app/src/main/res/layout/activity_main.xml
>          android:layout_marginBottom="35dp"
revisto

2020-03-10 14:03 UTC, ntsmoura commented on TopMovies/app/src/main/res/layout/movie_layout.xml
> +                android:focusable="auto" />
revisto

2020-03-26 22:44 UTC, pablohildo requested changes

2020-03-26 22:44 UTC, pablohildo commented on TopMovies/.idea/codeStyles/Project.xml
>  <component name="ProjectCodeStyleConfiguration">
Você colocou no gitignore e não removeu a pasta

2020-03-26 22:44 UTC, pablohildo commented on TopMovies/app/src/main/AndroidManifest.xml
> +        <activity android:name="com.ntsmoura.topmovies.activities.DescriptionActivity" android:screenOrientation="portrait"></activity>
Você pode usar autoclosing tag
Invés de 
`<activity></activity>`
Usar 
`<activity />`

2020-03-26 22:44 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/adapters/MovieAdapter.kt
> +    override fun getItemCount(): Int {
```suggestion+2
    override fun getItemCount(): Int = movieList.size
```

2020-03-26 22:44 UTC, pablohildo commented on TopMovies/app/src/main/res/values/strings.xml
> +    <string name="poster_content">Pôster de </string>
Pesquisar por `%s`

2020-03-26 22:45 UTC, pablohildo commented on TopMovies/.idea/misc.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Colocou no gitignore e não removeu

2020-03-26 22:45 UTC, pablohildo commented on TopMovies/.idea/gradle.xml
>  <?xml version="1.0" encoding="UTF-8"?>
Colocou no gitignore e não removeu

2020-03-26 22:45 UTC, pablohildo commented on TopMovies/.idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Colocou no gitignore e não removeu

2020-03-26 22:46 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/activities/DescriptionActivity.kt
> +        val title = intent.getStringExtra("movieTitle")
dá pra usar `with` aqui

2020-03-26 22:46 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/activities/MainActivity.kt
> +        mainRV.layoutManager = GridLayoutManager(this@MainActivity, 2)
Dá pra usar `apply` aqui

2020-03-26 22:47 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/adapters/MovieAdapter.kt
> +        val v = LayoutInflater.from(parent.context).inflate(R.layout.movie_layout, parent, false)
Se você tá passando o `context` no construtor do `MovieAdapter`, provavelmente é ele que ce devia estar usando aqui. Ou isso ou é possível que você não precise desse construtor.

2020-03-26 22:48 UTC, pablohildo commented on TopMovies/app/src/main/java/com/ntsmoura/topmovies/adapters/MovieAdapter.kt
> +            itemView.posterIMG.contentDescription = R.string.poster_content.toString() + movie.title
Dá pra usar `apply` aqui

2020-08-07 18:11 UTC, merged